openapi: 3.1.0

info:
  title: Event Management API
  description: Event Management allows users to create, read, update and delete Events and Event Types
  version: '3.17.0'
  x-visibility: external

servers:
  - url: https://api.eu1.siemens.app/eventmanagement-1000001700/v3
    description: Xcelerator compliant URL
  - url: https://gateway.eu1.mindsphere.io/api/eventmanagement/v3
    description: IH compliant URL

tags:
  - name: event management billboard
    description: Event management billboard operations
  - name: events
    description: Event operations
  - name: event types
    description: Event type operations
  - name: jobs
    description: Job operations

paths:
  /:
    get:
      operationId: infoAPI
      summary: Info about the API
      description: Ideally, the billboard URI is the only address a REST client needs to know. From there onwards, it must be able to discover all other URIs of the service by using the returned
      tags:
        - event management billboard
      security:
        - event:
            - em.r
  /events:
    post:
      operationId: createEvent
      summary: Create new event
      description: |
        Creates an event with the provided content (`Event` model can be used).

        \
        If no `typeId` is given in the request, then a `MindsphereStandardEvent` will be created. A standard event has 5 additional fields beside the fields defined in the `Event` data model
          - `description` (string, not required, not filterable, updatable)
          - `severity` (integer, not required, filterable, updatable)
          - `code` (string, not required, filterable, updatable)
          - `source` (string, not required, filterable, updatable)
          - `acknowledged` (boolean, not required, filterable, updatable)

        If there is a valid `typeId` in the request body then the event DTO must match to the corresponding event type given by the `typeId`. All the required fields from given 'typeId' and its parent eventTypes in the hierarchy should be included in the event payload when creating a custom event

        \
        **!Restriction!**
        - **After successful response, it may take 100ms to make it visible to the user.**
      tags:
        - events
      security:
        - event:
            - em.c
          eventType:
            - em.et.r
    get:
      operationId: queryEvents
      summary: Query events
      description: |
        Returns events based on the request parameters. If no `typeId` is given in the filter expression then `MindsphereStandardEvent` typed events (and its descendants excluding descendant specific fields) will be returned.

        \
        **Note:**
        **Clients must always expect incompleteness of the list of returned events, as internal processing is limited by eventual consistency.**
      security:
        - event:
            - em.r
      tags:
        - events
  /events/{eventId}:
    get:
      operationId: retrieveEvent
      summary: Get an event
      description: |
        Returns an event by ID.
      tags:
        - events
      security:
        - event:
            - em.r
    put:
      operationId: updateEvent
      summary: Update an event
      description: |
        Update an existing event by ID.

        \
        If user wants to have history of an event, it can be done to use POST request having the same `typeId`, `correlationId` and `entityId` in the payload.

        \
        **!Restriction!**
        - **PUT endpoint can only be used for content adjustments (corrections) but not for status changes (e.g. tickets use case). The time range for changes (updating an event by ID) might be limited in upcoming versions.**
        - **Recommended usage for status changes is the update simulation based on an existing event's correlation ID and entity ID via POST endpoint.**
        - **After successful response, it may take 100ms to make it visible to the user.**
        - **The following fields are required and their value cannot be changed**
          - **`correlationId`**
          - **`timestamp`**
          - **`entityId`**
        - **`typeId` cannot be changed, and is required for Custom events**
      tags:
        - events
      security:
        - event:
            - em.u
          eventType:
            - em.et.r
  /eventTypes:
    post:
      operationId: createEventType
      summary: Create new event type
      description: |
        Creates an event type with the provided content.
        - Default `id` is generated UUID. If `id` is provided then it has to be prefixed with the current tenant and has to be followed by a dot.
        - Default `parentId` is `BaseEvent`
        - Default `ttl` value is 35
        - Default `scope` is LOCAL
        - Default `filterable` value for a field is false
        - Default `required` value for a field is false
        - Default `updatable` value for a field is true
        - Clients must provide `values` field in case of ENUM type and must not provide in case of any other field type.

        \
        **!Restriction!**
        - **After successful response, it may take 100ms to make it visible to the user.**
      tags:
        - event types
      security:
        - eventType:
            - em.et.c
    get:
      operationId: queryEventTypes
      summary: Query event types
      description: |
        Returns event types based on the request parameters.

        \
        **!Note!**
        - **In case of sub-tenant user, global and related T1 local event types are also visible.**
      tags:
        - event types
      security:
        - eventType:
            - em.et.r
  /eventTypes/{eventTypeId}:
    patch:
      operationId: updateEventType
      summary: Update an event type
      description: |
        Updates an event type by ID by only sending the changed content.

        \
        **!Restriction!**
        - **After successful response, it may take 100ms to make it visible to the user.**
      tags:
        - event types
      security:
        - eventType:
            - em.et.u
    get:
      operationId: retrieveEventType
      summary: Get an event type
      description: |
        Returns an event type by ID.

        \
        **!Note!**
        - **In case of sub-tenant user, global and related T1 local event types are also visible.**
      tags:
        - event types
      security:
        - eventType:
            - em.et.r
    delete:
      operationId: deleteEventType
      summary: Delete an event type
      description: |
        Delets an event type by ID.
      tags:
        - event types
      security:
        - eventType:
            - em.et.d
  /deleteEventsJobs:
    post:
      operationId: createEventDeletionJob
      summary: Create a delete events job
      description: |
        Creates an asynchronous job which deletes events based on filter expression. Maximum 1.000.000 events can be deleted at once. The job status can be queried for 2 hours at most after the jobID is returned.
        If the latest event instance in a history of an event is deleted then the history of the event will be deleted.

        \
        **!Restriction!**
        Job will result in `FINISHED_WITH_ERROR` state in cases you can find below
        - **Concurrent event deletion on the same event type is not allowed.**
        - **Concurrent event deletion and event type modification for the same event type is not allowed.**
      security:
        - event:
            - em.d
          job:
            - em.dej.c
          eventType:
            - em.et.r
      tags:
        - jobs
  /deleteEventsJobs/{jobId}:
    get:
      operationId: retrieveEventDeletionJob
      summary: Get a delete events job
      description: |
        Returns a delete events job state by ID.
      tags:
        - jobs
      security:
        - job:
            - em.dej.r
  /createEventsJobs:
    post:
      operationId: createEventCreationJob
      summary: Create a create events job
      description: |
        Creates an asynchronous job which creates events with the provided content. Maximum 150 events can be created at once. The job status can be queried for 2 hours at most after the jobID is returned.
      security:
        - event:
            - em.c
          job:
            - em.cej.c
          eventType:
            - em.et.r
      tags:
        - jobs
  /createEventsJobs/{jobId}:
    get:
      operationId: retrieveEventCreationJob
      summary: Get a create events job
      description: |
        Returns a create events job state by ID.
      tags:
        - jobs
      security:
        - job:
            - em.cej.r
components:
  securitySchemes:
    event:
      type: oauth2
      description: |
        For **Xcelerator** compliance, please use **authorizationUrl** = https://1000001700.eu1.sws.siemens.com/oauth/authorize and **tokenUrl** = https://1000001700.eu1.sws.siemens.com/oauth/token

        For **IH** compliance, please use **authorizationUrl** = https://core.piam.eu1.mindsphere.io/oauth/authorize and **tokenUrl** = https://core.piam.eu1.mindsphere.io/oauth/token
      flows:
        authorizationCode:
          authorizationUrl: 'https://1000001700.eu1.sws.siemens.com/oauth/authorize'
          tokenUrl: 'https://1000001700.eu1.sws.siemens.com/oauth/token'
          scopes:
            em.c: create event
            em.r: read event
            em.u: update event
            em.d: delete event
    eventType:
      type: oauth2
      description: |
        For **Xcelerator** compliance, please use **authorizationUrl** = https://1000001700.eu1.sws.siemens.com/oauth/authorize and **tokenUrl** = https://1000001700.eu1.sws.siemens.com/oauth/token

        For **IH** compliance, please use **authorizationUrl** = https://core.piam.eu1.mindsphere.io/oauth/authorize and **tokenUrl** = https://core.piam.eu1.mindsphere.io/oauth/token
      flows:
        authorizationCode:
          authorizationUrl: 'https://1000001700.eu1.sws.siemens.com/oauth/authorize'
          tokenUrl: 'https://1000001700.eu1.sws.siemens.com/oauth/token'
          scopes:
            em.et.c: create event type
            em.et.r: read event type
            em.et.u: update event type
            em.et.d: delete event type
    job:
      type: oauth2
      description: |
        For **Xcelerator** compliance, please use **authorizationUrl** = https://1000001700.eu1.sws.siemens.com/oauth/authorize and **tokenUrl** = https://1000001700.eu1.sws.siemens.com/oauth/token

        For **IH** compliance, please use **authorizationUrl** = https://core.piam.eu1.mindsphere.io/oauth/authorize and **tokenUrl** = https://core.piam.eu1.mindsphere.io/oauth/token
      flows:
        authorizationCode:
          authorizationUrl: 'https://1000001700.eu1.sws.siemens.com/oauth/authorize'
          tokenUrl: 'https://1000001700.eu1.sws.siemens.com/oauth/token'
          scopes:
            em.dej.c: create delete events job
            em.dej.r: read delete events job
            em.cej.c: create create events job
            em.cej.r: read create events job
